// TIME TRAVELLER — Event Database
// 69 events: T1-001–T1-021 | T2-001–T2-024 | T3-001–T3-024
//
// yaw: initial camera direction (0=forward, 90=right, 180=back, 270=left)

var EVENTS = [
  {
    id:         'T1-001',
    name:       "D-Day \u2013 Normandy Landings",
    year:       1944,
    lat:        49.3667,
    lng:        -0.8667,
    loc:        "Omaha Beach, Normandy",
    img:        'T1-001_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "20th Century AD",
    c3:         "Omaha Beach, Normandy, France",
    desc:       "D-Day \u2013 Normandy Landings. Omaha Beach, Normandy, June 6, 1944 AD.",
    wikiImg:    "",
    wikiTitle:  "D-Day \u2013 Normandy Landings"
  },
  {
    id:         'T1-002',
    name:       "Fall of Constantinople",
    year:       1453,
    lat:        41.0082,
    lng:        28.9784,
    loc:        "Constantinople (Istanbul)",
    img:        'T1-002_img1.png',
    yaw:        0,
    c1:         "Europe/Asia",
    c2:         "15th Century AD",
    c3:         "Constantinople (Istanbul), Turkey",
    desc:       "Fall of Constantinople. Constantinople (Istanbul), May 29, 1453 AD.",
    wikiImg:    "",
    wikiTitle:  "Fall of Constantinople"
  },
  {
    id:         'T1-003',
    name:       "Eruption of Vesuvius \u2013 Destruction of Pompeii",
    year:       79,
    lat:        40.7491,
    lng:        14.4897,
    loc:        "Pompeii, Campania",
    img:        'T1-003_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "1st Century AD",
    c3:         "Pompeii, Campania, Italy",
    desc:       "Eruption of Vesuvius \u2013 Destruction of Pompeii. Pompeii, Campania, 79 AD.",
    wikiImg:    "",
    wikiTitle:  "Eruption of Vesuvius \u2013 Destruction of Pompeii"
  },
  {
    id:         'T1-004',
    name:       "Storming of the Bastille \u2013 French Revolution",
    year:       1789,
    lat:        48.8533,
    lng:        2.3692,
    loc:        "Place de la Bastille, Paris",
    img:        'T1-004_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "18th Century AD",
    c3:         "Place de la Bastille, Paris, France",
    desc:       "Storming of the Bastille \u2013 French Revolution. Place de la Bastille, Paris, July 14, 1789 AD.",
    wikiImg:    "",
    wikiTitle:  "Storming of the Bastille \u2013 French Revolution"
  },
  {
    id:         'T1-005',
    name:       "Great Fire of London",
    year:       1666,
    lat:        51.5074,
    lng:        -0.0983,
    loc:        "City of London",
    img:        'T1-005_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "17th Century AD",
    c3:         "City of London, United Kingdom",
    desc:       "Great Fire of London. City of London, September 2\u20135, 1666 AD.",
    wikiImg:    "",
    wikiTitle:  "Great Fire of London"
  },
  {
    id:         'T1-006',
    name:       "Assassination of Julius Caesar",
    year:       -44,
    lat:        41.8955,
    lng:        12.4823,
    loc:        "Theatre of Pompey, Rome",
    img:        'T1-006_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "1st Century BC",
    c3:         "Theatre of Pompey, Rome, Italy",
    desc:       "Assassination of Julius Caesar. Theatre of Pompey, Rome, March 15, 44 BC.",
    wikiImg:    "",
    wikiTitle:  "Assassination of Julius Caesar"
  },
  {
    id:         'T1-007',
    name:       "Black Death Reaches Western Europe",
    year:       1347,
    yearMin:    1347,
    yearMax:    1353,
    lat:        43.2965,
    lng:        5.3698,
    loc:        "Port of Marseille, France",
    img:        'T1-007_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "14th Century AD",
    c3:         "Port of Marseille, France, France",
    desc:       "Black Death Reaches Western Europe. Port of Marseille, France, 1347 AD.",
    wikiImg:    "",
    wikiTitle:  "Black Death Reaches Western Europe"
  },
  {
    id:         'T1-008',
    name:       "Battle of Waterloo",
    year:       1815,
    lat:        50.6796,
    lng:        4.4122,
    loc:        "Waterloo, Belgium",
    img:        'T1-008_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "19th Century AD",
    c3:         "Waterloo, Belgium, Belgium",
    desc:       "Battle of Waterloo. Waterloo, Belgium, June 18, 1815 AD.",
    wikiImg:    "",
    wikiTitle:  "Battle of Waterloo"
  },
  {
    id:         'T1-009',
    name:       "Apollo 11 Moon Landing",
    year:       1969,
    lat:        28.5721,
    lng:        -80.648,
    loc:        "Kennedy Space Center, Florida, USA (mission launch site \u2014 event occurred on the Moon)",
    img:        'T1-009_img1.png',
    yaw:        0,
    c1:         "",
    c2:         "20th Century AD",
    c3:         "Kennedy Space Center, Florida, USA (mission launch site \u2014 event occurred on the Moon), USA",
    desc:       "Apollo 11 Moon Landing. Kennedy Space Center, Florida, USA (mission launch site \u2014 event occurred on the Moon), July 20, 1969 AD.",
    wikiImg:    "",
    wikiTitle:  "Apollo 11 Moon Landing",
    moonEvent:  true
  },
  {
    id:         'T1-010',
    name:       "Atomic Bombing of Hiroshima",
    year:       1945,
    lat:        34.3955,
    lng:        132.4536,
    loc:        "Hiroshima, Japan",
    img:        'T1-010_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "20th Century AD",
    c3:         "Hiroshima, Japan, Japan",
    desc:       "Atomic Bombing of Hiroshima. Hiroshima, Japan, August 6, 1945 AD.",
    wikiImg:    "",
    wikiTitle:  "Atomic Bombing of Hiroshima"
  },
  {
    id:         'T1-011',
    name:       "Russian Revolution \u2013 Storming of the Winter Palace",
    year:       1917,
    lat:        59.9398,
    lng:        30.3146,
    loc:        "Winter Palace, Petrograd (St Petersburg)",
    img:        'T1-011_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "20th Century AD",
    c3:         "Winter Palace, Petrograd (St Petersburg), Russia",
    desc:       "Russian Revolution \u2013 Storming of the Winter Palace. Winter Palace, Petrograd (St Petersburg), October 25, 1917 AD (Julian) / November 7, 1917 (Gregorian).",
    wikiImg:    "",
    wikiTitle:  "Russian Revolution \u2013 Storming of the Winter Palace"
  },
  {
    id:         'T1-012',
    name:       "WWI \u2013 Battle of the Somme (Trench Warfare)",
    year:       1916,
    yearMin:    1916,
    yearMax:    1916,
    lat:        50.001,
    lng:        2.686,
    loc:        "Somme, Northern France",
    img:        'T1-012_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "20th Century AD",
    c3:         "Somme, Northern France, France",
    desc:       "WWI \u2013 Battle of the Somme (Trench Warfare). Somme, Northern France, July 1 \u2013 November 18, 1916 AD.",
    wikiImg:    "",
    wikiTitle:  "WWI \u2013 Battle of the Somme (Trench Warfare)"
  },
  {
    id:         'T1-013',
    name:       "WWII \u2013 Battle of Stalingrad",
    year:       1942,
    yearMin:    1942,
    yearMax:    1943,
    lat:        48.708,
    lng:        44.5133,
    loc:        "Stalingrad (Volgograd), Russia",
    img:        'T1-013_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "20th Century AD",
    c3:         "Stalingrad (Volgograd), Russia, Russia",
    desc:       "WWII \u2013 Battle of Stalingrad. Stalingrad (Volgograd), Russia, August 23, 1942 \u2013 February 2, 1943 AD.",
    wikiImg:    "",
    wikiTitle:  "WWII \u2013 Battle of Stalingrad"
  },
  {
    id:         'T1-014',
    name:       "Attack on Pearl Harbor",
    year:       1941,
    lat:        21.3647,
    lng:        -157.9505,
    loc:        "Pearl Harbor, Oahu, Hawaii",
    img:        'T1-014_img1.png',
    yaw:        0,
    c1:         "Oceania/Pacific",
    c2:         "20th Century AD",
    c3:         "Pearl Harbor, Oahu, Hawaii, USA",
    desc:       "Attack on Pearl Harbor. Pearl Harbor, Oahu, Hawaii, December 7, 1941 AD.",
    wikiImg:    "",
    wikiTitle:  "Attack on Pearl Harbor"
  },
  {
    id:         'T1-015',
    name:       "Fall of the Berlin Wall",
    year:       1989,
    lat:        52.5163,
    lng:        13.3777,
    loc:        "Brandenburg Gate, Berlin",
    img:        'T1-015_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "20th Century AD",
    c3:         "Brandenburg Gate, Berlin, Germany",
    desc:       "Fall of the Berlin Wall. Brandenburg Gate, Berlin, November 9, 1989 AD.",
    wikiImg:    "",
    wikiTitle:  "Fall of the Berlin Wall"
  },
  {
    id:         'T1-016',
    name:       "Crucifixion of Jesus Christ",
    year:       30,
    yearMin:    30,
    yearMax:    33,
    lat:        31.7784,
    lng:        35.2296,
    loc:        "Golgotha (Church of the Holy Sepulchre), Jerusalem",
    img:        'T1-016_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "1st Century AD",
    c3:         "Golgotha (Church of the Holy Sepulchre), Jerusalem, Israel",
    desc:       "Crucifixion of Jesus Christ. Golgotha (Church of the Holy Sepulchre), Jerusalem, c. 30\u201333 AD.",
    wikiImg:    "",
    wikiTitle:  "Crucifixion of Jesus Christ"
  },
  {
    id:         'T1-017',
    name:       "Napoleon's Coronation as Emperor",
    year:       1804,
    lat:        48.853,
    lng:        2.3499,
    loc:        "Notre-Dame Cathedral, Paris",
    img:        'T1-017_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "19th Century AD",
    c3:         "Notre-Dame Cathedral, Paris, France",
    desc:       "Napoleon's Coronation as Emperor. Notre-Dame Cathedral, Paris, December 2, 1804 AD.",
    wikiImg:    "",
    wikiTitle:  "Napoleon's Coronation as Emperor"
  },
  {
    id:         'T1-018',
    name:       "Battle of Gettysburg",
    year:       1863,
    yearMin:    1863,
    yearMax:    1863,
    lat:        39.8112,
    lng:        -77.2253,
    loc:        "Gettysburg, Pennsylvania",
    img:        'T1-018_img1.png',
    yaw:        0,
    c1:         "North America",
    c2:         "19th Century AD",
    c3:         "Gettysburg, Pennsylvania, USA",
    desc:       "Battle of Gettysburg. Gettysburg, Pennsylvania, July 1\u20133, 1863 AD.",
    wikiImg:    "",
    wikiTitle:  "Battle of Gettysburg"
  },
  {
    id:         'T1-019',
    name:       "Cuban Missile Crisis \u2013 Naval Blockade",
    year:       1962,
    yearMin:    1962,
    yearMax:    1962,
    lat:        23.1136,
    lng:        -82.3666,
    loc:        "Havana / Caribbean Sea, Cuba",
    img:        'T1-019_img1.png',
    yaw:        0,
    c1:         "North America",
    c2:         "20th Century AD",
    c3:         "Havana / Caribbean Sea, Cuba, Cuba",
    desc:       "Cuban Missile Crisis \u2013 Naval Blockade. Havana / Caribbean Sea, Cuba, October 16\u201328, 1962 AD.",
    wikiImg:    "",
    wikiTitle:  "Cuban Missile Crisis \u2013 Naval Blockade"
  },
  {
    id:         'T1-020',
    name:       "Liberation of Paris \u2013 WWII",
    year:       1944,
    yearMin:    1944,
    yearMax:    1944,
    lat:        48.8738,
    lng:        2.295,
    loc:        "Champs-\u00c9lys\u00e9es, Paris",
    img:        'T1-020_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "20th Century AD",
    c3:         "Champs-\u00c9lys\u00e9es, Paris, France",
    desc:       "Liberation of Paris \u2013 WWII. Champs-\u00c9lys\u00e9es, Paris, August 19\u201325, 1944 AD.",
    wikiImg:    "",
    wikiTitle:  "Liberation of Paris \u2013 WWII"
  },
  {
    id:         'T1-021',
    name:       "Dunkirk Evacuation \u2013 Operation Dynamo",
    year:       1940,
    yearMin:    1940,
    yearMax:    1940,
    lat:        51.0344,
    lng:        2.3767,
    loc:        "Dunkirk beach, Northern France",
    img:        'T1-021_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "20th Century AD",
    c3:         "Dunkirk beach, Northern France, France",
    desc:       "Dunkirk Evacuation \u2013 Operation Dynamo. Dunkirk beach, Northern France, May 26 \u2013 June 4, 1940 AD.",
    wikiImg:    "",
    wikiTitle:  "Dunkirk Evacuation \u2013 Operation Dynamo"
  },
  {
    id:         'T2-001',
    name:       "Battle of Thermopylae",
    year:       -480,
    lat:        38.7956,
    lng:        22.5339,
    loc:        "Thermopylae Pass, Greece",
    img:        'T2-001_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "5th Century BC",
    c3:         "Thermopylae Pass, Greece, Greece",
    desc:       "Battle of Thermopylae. Thermopylae Pass, Greece, 480 BC.",
    wikiImg:    "",
    wikiTitle:  "Battle of Thermopylae"
  },
  {
    id:         'T2-002',
    name:       "Mongol Sack of Baghdad",
    year:       1258,
    lat:        33.3406,
    lng:        44.4009,
    loc:        "Baghdad, Iraq",
    img:        'T2-002_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "13th Century AD",
    c3:         "Baghdad, Iraq, Iraq",
    desc:       "Mongol Sack of Baghdad. Baghdad, Iraq, February 1258 AD.",
    wikiImg:    "",
    wikiTitle:  "Mongol Sack of Baghdad"
  },
  {
    id:         'T2-003',
    name:       "Signing of Magna Carta",
    year:       1215,
    lat:        51.439,
    lng:        -0.568,
    loc:        "Runnymede, Surrey, England",
    img:        'T2-003_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "13th Century AD",
    c3:         "Runnymede, Surrey, England, United Kingdom",
    desc:       "Signing of Magna Carta. Runnymede, Surrey, England, June 15, 1215 AD.",
    wikiImg:    "",
    wikiTitle:  "Signing of Magna Carta"
  },
  {
    id:         'T2-004',
    name:       "Battle of Hastings",
    year:       1066,
    lat:        50.9098,
    lng:        0.4876,
    loc:        "Senlac Hill, Battle, East Sussex",
    img:        'T2-004_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "11th Century AD",
    c3:         "Senlac Hill, Battle, East Sussex, United Kingdom",
    desc:       "Battle of Hastings. Senlac Hill, Battle, East Sussex, October 14, 1066 AD.",
    wikiImg:    "",
    wikiTitle:  "Battle of Hastings"
  },
  {
    id:         'T2-005',
    name:       "Boston Tea Party",
    year:       1773,
    lat:        42.3536,
    lng:        -71.05,
    loc:        "Griffin's Wharf, Boston",
    img:        'T2-005_img1.png',
    yaw:        0,
    c1:         "North America",
    c2:         "18th Century AD",
    c3:         "Griffin's Wharf, Boston, USA",
    desc:       "Boston Tea Party. Griffin's Wharf, Boston, December 16, 1773 AD.",
    wikiImg:    "",
    wikiTitle:  "Boston Tea Party"
  },
  {
    id:         'T2-006',
    name:       "Columbus Reaches the Americas",
    year:       1492,
    lat:        24.05,
    lng:        -74.5333,
    loc:        "San Salvador Island, Bahamas",
    img:        'T2-006_img1.png',
    yaw:        0,
    c1:         "North America",
    c2:         "15th Century AD",
    c3:         "San Salvador Island, Bahamas, Bahamas",
    desc:       "Columbus Reaches the Americas. San Salvador Island, Bahamas, October 12, 1492 AD.",
    wikiImg:    "",
    wikiTitle:  "Columbus Reaches the Americas"
  },
  {
    id:         'T2-007',
    name:       "Sack of Rome by the Visigoths",
    year:       410,
    lat:        41.8892,
    lng:        12.4921,
    loc:        "Rome, Italy",
    img:        'T2-007_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "5th Century AD",
    c3:         "Rome, Italy, Italy",
    desc:       "Sack of Rome by the Visigoths. Rome, Italy, August 410 AD.",
    wikiImg:    "",
    wikiTitle:  "Sack of Rome by the Visigoths"
  },
  {
    id:         'T2-008',
    name:       "Gutenberg Prints the Bible",
    year:       1454,
    yearMin:    1454,
    yearMax:    1456,
    lat:        49.9929,
    lng:        8.2473,
    loc:        "Mainz, Germany",
    img:        'T2-008_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "15th Century AD",
    c3:         "Mainz, Germany, Germany",
    desc:       "Gutenberg Prints the Bible. Mainz, Germany, c. 1455 AD.",
    wikiImg:    "",
    wikiTitle:  "Gutenberg Prints the Bible"
  },
  {
    id:         'T2-009',
    name:       "Battle of Gaugamela \u2013 Alexander vs Darius III",
    year:       -331,
    lat:        36.36,
    lng:        43.25,
    loc:        "Gaugamela, near Mosul, Iraq",
    img:        'T2-009_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "4th Century BC",
    c3:         "Gaugamela, near Mosul, Iraq, Iraq",
    desc:       "Battle of Gaugamela \u2013 Alexander vs Darius III. Gaugamela, near Mosul, Iraq, October 1, 331 BC.",
    wikiImg:    "",
    wikiTitle:  "Battle of Gaugamela \u2013 Alexander vs Darius III"
  },
  {
    id:         'T2-010',
    name:       "Haitian Revolution \u2013 Declaration of Independence",
    year:       1804,
    lat:        19.76,
    lng:        -72.2,
    loc:        "Gona\u00efves, Haiti",
    img:        'T2-010_img1.png',
    yaw:        0,
    c1:         "North America",
    c2:         "19th Century AD",
    c3:         "Gona\u00efves, Haiti, Haiti",
    desc:       "Haitian Revolution \u2013 Declaration of Independence. Gona\u00efves, Haiti, January 1, 1804 AD.",
    wikiImg:    "",
    wikiTitle:  "Haitian Revolution \u2013 Declaration of Independence"
  },
  {
    id:         'T2-011',
    name:       "Charlemagne's Coronation as Holy Roman Emperor",
    year:       800,
    lat:        41.9022,
    lng:        12.4539,
    loc:        "Old St. Peter's Basilica, Rome",
    img:        'T2-011_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "8th Century AD",
    c3:         "Old St. Peter's Basilica, Rome, Italy",
    desc:       "Charlemagne's Coronation as Holy Roman Emperor. Old St. Peter's Basilica, Rome, December 25, 800 AD.",
    wikiImg:    "",
    wikiTitle:  "Charlemagne's Coronation as Holy Roman Emperor"
  },
  {
    id:         'T2-012',
    name:       "Great Schism \u2013 Excommunication of the Orthodox Patriarch",
    year:       1054,
    lat:        41.0086,
    lng:        28.9802,
    loc:        "Hagia Sophia, Constantinople",
    img:        'T2-012_img1.png',
    yaw:        0,
    c1:         "Europe/Asia",
    c2:         "11th Century AD",
    c3:         "Hagia Sophia, Constantinople, Turkey",
    desc:       "Great Schism \u2013 Excommunication of the Orthodox Patriarch. Hagia Sophia, Constantinople, July 16, 1054 AD.",
    wikiImg:    "",
    wikiTitle:  "Great Schism \u2013 Excommunication of the Orthodox Patriarch"
  },
  {
    id:         'T2-013',
    name:       "First Crusade \u2013 Siege of Jerusalem",
    year:       1099,
    yearMin:    1099,
    yearMax:    1099,
    lat:        31.7767,
    lng:        35.2345,
    loc:        "Jerusalem",
    img:        'T2-013_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "11th Century AD",
    c3:         "Jerusalem, Israel",
    desc:       "First Crusade \u2013 Siege of Jerusalem. Jerusalem, June 7 \u2013 July 15, 1099 AD.",
    wikiImg:    "",
    wikiTitle:  "First Crusade \u2013 Siege of Jerusalem"
  },
  {
    id:         'T2-014',
    name:       "Battle of Austerlitz \u2013 Napoleon's Greatest Victory",
    year:       1805,
    lat:        49.0292,
    lng:        16.77,
    loc:        "Austerlitz (Slavkov), Czech Republic",
    img:        'T2-014_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "19th Century AD",
    c3:         "Austerlitz (Slavkov), Czech Republic, Czech Republic",
    desc:       "Battle of Austerlitz \u2013 Napoleon's Greatest Victory. Austerlitz (Slavkov), Czech Republic, December 2, 1805 AD.",
    wikiImg:    "",
    wikiTitle:  "Battle of Austerlitz \u2013 Napoleon's Greatest Victory"
  },
  {
    id:         'T2-015',
    name:       "Fall of Saigon \u2013 Vietnam War",
    year:       1975,
    lat:        10.7757,
    lng:        106.7011,
    loc:        "Presidential Palace / US Embassy, Saigon (Ho Chi Minh City)",
    img:        'T2-015_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "20th Century AD",
    c3:         "Presidential Palace / US Embassy, Saigon (Ho Chi Minh City), Vietnam",
    desc:       "Fall of Saigon \u2013 Vietnam War. Presidential Palace / US Embassy, Saigon (Ho Chi Minh City), April 30, 1975 AD.",
    wikiImg:    "",
    wikiTitle:  "Fall of Saigon \u2013 Vietnam War"
  },
  {
    id:         'T2-016',
    name:       "Hijra \u2013 Muhammad's Migration to Medina",
    year:       622,
    lat:        24.4672,
    lng:        39.6024,
    loc:        "Medina (Yathrib), Arabian Peninsula",
    img:        'T2-016_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "7th Century AD",
    c3:         "Medina (Yathrib), Arabian Peninsula, Saudi Arabia",
    desc:       "Hijra \u2013 Muhammad's Migration to Medina. Medina (Yathrib), Arabian Peninsula, 622 AD.",
    wikiImg:    "",
    wikiTitle:  "Hijra \u2013 Muhammad's Migration to Medina"
  },
  {
    id:         'T2-017',
    name:       "Mao Zedong Proclaims the People's Republic of China",
    year:       1949,
    lat:        39.9087,
    lng:        116.3975,
    loc:        "Tiananmen Gate, Beijing",
    img:        'T2-017_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "20th Century AD",
    c3:         "Tiananmen Gate, Beijing, China",
    desc:       "Mao Zedong Proclaims the People's Republic of China. Tiananmen Gate, Beijing, October 1, 1949 AD.",
    wikiImg:    "",
    wikiTitle:  "Mao Zedong Proclaims the People's Republic of China"
  },
  {
    id:         'T2-018',
    name:       "Meiji Restoration \u2013 Japan Opens to the World",
    year:       1868,
    lat:        35.0235,
    lng:        135.768,
    loc:        "Kyoto Imperial Palace, Japan",
    img:        'T2-018_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "19th Century AD",
    c3:         "Kyoto Imperial Palace, Japan, Japan",
    desc:       "Meiji Restoration \u2013 Japan Opens to the World. Kyoto Imperial Palace, Japan, 1868 AD.",
    wikiImg:    "",
    wikiTitle:  "Meiji Restoration \u2013 Japan Opens to the World"
  },
  {
    id:         'T2-019',
    name:       "Nanjing Massacre",
    year:       1937,
    yearMin:    1937,
    yearMax:    1938,
    lat:        32.0617,
    lng:        118.78,
    loc:        "Nanjing, China",
    img:        'T2-019_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "20th Century AD",
    c3:         "Nanjing, China, China",
    desc:       "Nanjing Massacre. Nanjing, China, December 1937 \u2013 January 1938 AD.",
    wikiImg:    "",
    wikiTitle:  "Nanjing Massacre"
  },
  {
    id:         'T2-020',
    name:       "Spanish Armada \u2013 Battle off Gravelines",
    year:       1588,
    lat:        51.01,
    lng:        2.13,
    loc:        "Off Gravelines, English Channel, France/Belgium",
    img:        'T2-020_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "16th Century AD",
    c3:         "Off Gravelines, English Channel, France/Belgium, France/Belgium (sea)",
    desc:       "Spanish Armada \u2013 Battle off Gravelines. Off Gravelines, English Channel, France/Belgium, August 8, 1588 AD.",
    wikiImg:    "",
    wikiTitle:  "Spanish Armada \u2013 Battle off Gravelines"
  },
  {
    id:         'T2-021',
    name:       "Hannibal Crosses the Alps",
    year:       -218,
    lat:        44.9,
    lng:        6.9,
    loc:        "Mont-Cenis or Clapier Pass, Alps",
    img:        'T2-021_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "3rd Century BC",
    c3:         "Mont-Cenis or Clapier Pass, Alps, France/Italy border",
    desc:       "Hannibal Crosses the Alps. Mont-Cenis or Clapier Pass, Alps, 218 BC.",
    wikiImg:    "",
    wikiTitle:  "Hannibal Crosses the Alps"
  },
  {
    id:         'T2-022',
    name:       "Conquest of Tenochtitlan by Hern\u00e1n Cort\u00e9s",
    year:       1521,
    lat:        19.4326,
    lng:        -99.1332,
    loc:        "Tenochtitlan (Mexico City), Mexico",
    img:        'T2-022_img1.png',
    yaw:        0,
    c1:         "North America",
    c2:         "16th Century AD",
    c3:         "Tenochtitlan (Mexico City), Mexico, Mexico",
    desc:       "Conquest of Tenochtitlan by Hern\u00e1n Cort\u00e9s. Tenochtitlan (Mexico City), Mexico, August 13, 1521 AD.",
    wikiImg:    "",
    wikiTitle:  "Conquest of Tenochtitlan by Hern\u00e1n Cort\u00e9s"
  },
  {
    id:         'T2-023',
    name:       "Gandhi's Salt March",
    year:       1930,
    yearMin:    1930,
    yearMax:    1930,
    lat:        20.9042,
    lng:        72.6368,
    loc:        "Dandi Beach, Gujarat, India",
    img:        'T2-023_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "20th Century AD",
    c3:         "Dandi Beach, Gujarat, India, India",
    desc:       "Gandhi's Salt March. Dandi Beach, Gujarat, India, March 12 \u2013 April 6, 1930 AD.",
    wikiImg:    "",
    wikiTitle:  "Gandhi's Salt March"
  },
  {
    id:         'T2-024',
    name:       "Korean War \u2013 Inchon Landing",
    year:       1950,
    lat:        37.4563,
    lng:        126.6142,
    loc:        "Inchon (Incheon), South Korea",
    img:        'T2-024_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "20th Century AD",
    c3:         "Inchon (Incheon), South Korea, South Korea",
    desc:       "Korean War \u2013 Inchon Landing. Inchon (Incheon), South Korea, September 15, 1950 AD.",
    wikiImg:    "",
    wikiTitle:  "Korean War \u2013 Inchon Landing"
  },
  {
    id:         'T3-001',
    name:       "Seneca Falls Convention",
    year:       1848,
    lat:        42.9107,
    lng:        -76.7968,
    loc:        "Seneca Falls, New York State",
    img:        'T3-001_img1.png',
    yaw:        0,
    c1:         "North America",
    c2:         "19th Century AD",
    c3:         "Seneca Falls, New York State, USA",
    desc:       "Seneca Falls Convention. Seneca Falls, New York State, July 19\u201320, 1848 AD.",
    wikiImg:    "",
    wikiTitle:  "Seneca Falls Convention"
  },
  {
    id:         'T3-002',
    name:       "Daily Life in Ancient Uruk, Mesopotamia",
    year:       -3500,
    yearMin:    -3500,
    yearMax:    -3000,
    lat:        33.2232,
    lng:        43.6793,
    loc:        "Mesopotamia (modern central Iraq)",
    img:        'T3-002_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "35th Century BC",
    c3:         "Mesopotamia (modern central Iraq), Iraq",
    desc:       "Daily Life in Ancient Uruk, Mesopotamia. Mesopotamia (modern central Iraq), c. 3500\u20133000 BC.",
    wikiImg:    "",
    wikiTitle:  "Daily Life in Ancient Uruk, Mesopotamia"
  },
  {
    id:         'T3-003',
    name:       "Council of Nicaea \u2013 First Ecumenical Council",
    year:       325,
    lat:        40.4272,
    lng:        29.7233,
    loc:        "Nicaea (modern \u0130znik), Turkey",
    img:        'T3-003_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "4th Century AD",
    c3:         "Nicaea (modern \u0130znik), Turkey, Turkey",
    desc:       "Council of Nicaea \u2013 First Ecumenical Council. Nicaea (modern \u0130znik), Turkey, May\u2013August 325 AD.",
    wikiImg:    "",
    wikiTitle:  "Council of Nicaea \u2013 First Ecumenical Council"
  },
  {
    id:         'T3-004',
    name:       "Battle of Adwa \u2013 Ethiopia Defeats Italy",
    year:       1896,
    lat:        14.1667,
    lng:        38.9,
    loc:        "Adwa, Tigray, Ethiopia",
    img:        'T3-004_img1.png',
    yaw:        0,
    c1:         "Africa",
    c2:         "19th Century AD",
    c3:         "Adwa, Tigray, Ethiopia, Ethiopia",
    desc:       "Battle of Adwa \u2013 Ethiopia Defeats Italy. Adwa, Tigray, Ethiopia, March 1, 1896 AD.",
    wikiImg:    "",
    wikiTitle:  "Battle of Adwa \u2013 Ethiopia Defeats Italy"
  },
  {
    id:         'T3-005',
    name:       "Siege of Masada",
    year:       73,
    yearMin:    73,
    yearMax:    74,
    lat:        31.3156,
    lng:        35.3536,
    loc:        "Masada fortress, Judean Desert",
    img:        'T3-005_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "1st Century AD",
    c3:         "Masada fortress, Judean Desert, Israel",
    desc:       "Siege of Masada. Masada fortress, Judean Desert, 73\u201374 AD.",
    wikiImg:    "",
    wikiTitle:  "Siege of Masada"
  },
  {
    id:         'T3-006',
    name:       "Destruction of Carthage \u2013 Third Punic War",
    year:       -146,
    lat:        36.8528,
    lng:        10.3233,
    loc:        "Carthage, near Tunis, Tunisia",
    img:        'T3-006_img1.png',
    yaw:        0,
    c1:         "Africa",
    c2:         "2nd Century BC",
    c3:         "Carthage, near Tunis, Tunisia, Tunisia",
    desc:       "Destruction of Carthage \u2013 Third Punic War. Carthage, near Tunis, Tunisia, 146 BC.",
    wikiImg:    "",
    wikiTitle:  "Destruction of Carthage \u2013 Third Punic War"
  },
  {
    id:         'T3-007',
    name:       "Partition of India",
    year:       1947,
    lat:        31.604,
    lng:        74.5284,
    loc:        "Wagah, Punjab (India-Pakistan border)",
    img:        'T3-007_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "20th Century AD",
    c3:         "Wagah, Punjab (India-Pakistan border), India/Pakistan",
    desc:       "Partition of India. Wagah, Punjab (India-Pakistan border), August 14\u201315, 1947 AD.",
    wikiImg:    "",
    wikiTitle:  "Partition of India"
  },
  {
    id:         'T3-008',
    name:       "Foundation of Rome",
    year:       -753,
    yearMin:    -753,
    yearMax:    -625,
    lat:        41.8902,
    lng:        12.49,
    loc:        "Palatine Hill, Rome",
    img:        'T3-008_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "8th Century BC",
    c3:         "Palatine Hill, Rome, Italy",
    desc:       "Foundation of Rome. Palatine Hill, Rome, c. 753 BC (traditional).",
    wikiImg:    "",
    wikiTitle:  "Foundation of Rome"
  },
  {
    id:         'T3-009',
    name:       "Great Pyramid of Giza \u2013 Construction",
    year:       -2600,
    yearMin:    -2600,
    yearMax:    -2500,
    lat:        29.9792,
    lng:        31.1342,
    loc:        "Giza Plateau, Egypt",
    img:        'T3-009_img1.png',
    yaw:        0,
    c1:         "Africa",
    c2:         "26th Century BC",
    c3:         "Giza Plateau, Egypt, Egypt",
    desc:       "Great Pyramid of Giza \u2013 Construction. Giza Plateau, Egypt, c. 2560 BC.",
    wikiImg:    "",
    wikiTitle:  "Great Pyramid of Giza \u2013 Construction"
  },
  {
    id:         'T3-010',
    name:       "Siege of Troy",
    year:       -1260,
    yearMin:    -1260,
    yearMax:    -1180,
    lat:        39.9572,
    lng:        26.2387,
    loc:        "Hisarlik, \u00c7anakkale, Turkey",
    img:        'T3-010_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "13th Century BC",
    c3:         "Hisarlik, \u00c7anakkale, Turkey, Turkey",
    desc:       "Siege of Troy. Hisarlik, \u00c7anakkale, Turkey, c. 1180 BC (traditional).",
    wikiImg:    "",
    wikiTitle:  "Siege of Troy"
  },
  {
    id:         'T3-011',
    name:       "School of Athens \u2013 Socrates Teaching in the Agora",
    year:       -430,
    yearMin:    -430,
    yearMax:    -399,
    lat:        37.9755,
    lng:        23.7235,
    loc:        "Ancient Agora of Athens, Greece",
    img:        'T3-011_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "5th Century BC",
    c3:         "Ancient Agora of Athens, Greece, Greece",
    desc:       "School of Athens \u2013 Socrates Teaching in the Agora. Ancient Agora of Athens, Greece, c. 430\u2013399 BC.",
    wikiImg:    "",
    wikiTitle:  "School of Athens \u2013 Socrates Teaching in the Agora"
  },
  {
    id:         'T3-012',
    name:       "Trial of Socrates",
    year:       -399,
    lat:        37.974,
    lng:        23.726,
    loc:        "Court of the Heliaia, Athens",
    img:        'T3-012_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "4th Century BC",
    c3:         "Court of the Heliaia, Athens, Greece",
    desc:       "Trial of Socrates. Court of the Heliaia, Athens, 399 BC.",
    wikiImg:    "",
    wikiTitle:  "Trial of Socrates"
  },
  {
    id:         'T3-013',
    name:       "Viking Raid on Lindisfarne",
    year:       793,
    lat:        55.6814,
    lng:        -1.7993,
    loc:        "Holy Island (Lindisfarne), Northumberland",
    img:        'T3-013_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "8th Century AD",
    c3:         "Holy Island (Lindisfarne), Northumberland, United Kingdom",
    desc:       "Viking Raid on Lindisfarne. Holy Island (Lindisfarne), Northumberland, 793 AD.",
    wikiImg:    "",
    wikiTitle:  "Viking Raid on Lindisfarne"
  },
  {
    id:         'T3-014',
    name:       "Construction of the Great Wall of China \u2013 Qin Dynasty",
    year:       -221,
    yearMin:    -221,
    yearMax:    -206,
    lat:        40.4319,
    lng:        116.5704,
    loc:        "Badaling area, northern China",
    img:        'T3-014_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "3rd Century BC",
    c3:         "Badaling area, northern China, China",
    desc:       "Construction of the Great Wall of China \u2013 Qin Dynasty. Badaling area, northern China, c. 221\u2013206 BC.",
    wikiImg:    "",
    wikiTitle:  "Construction of the Great Wall of China \u2013 Qin Dynasty"
  },
  {
    id:         'T3-015',
    name:       "Battle of Sekigahara",
    year:       1600,
    lat:        35.3719,
    lng:        136.4709,
    loc:        "Sekigahara, Gifu Prefecture, Japan",
    img:        'T3-015_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "16th Century AD",
    c3:         "Sekigahara, Gifu Prefecture, Japan, Japan",
    desc:       "Battle of Sekigahara. Sekigahara, Gifu Prefecture, Japan, October 21, 1600 AD.",
    wikiImg:    "",
    wikiTitle:  "Battle of Sekigahara"
  },
  {
    id:         'T3-016',
    name:       "Construction of Angkor Wat",
    year:       1113,
    yearMin:    1113,
    yearMax:    1150,
    lat:        13.4125,
    lng:        103.867,
    loc:        "Angkor, Siem Reap, Cambodia",
    img:        'T3-016_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "12th Century AD",
    c3:         "Angkor, Siem Reap, Cambodia, Cambodia",
    desc:       "Construction of Angkor Wat. Angkor, Siem Reap, Cambodia, c. 1113\u20131150 AD.",
    wikiImg:    "",
    wikiTitle:  "Construction of Angkor Wat"
  },
  {
    id:         'T3-017',
    name:       "Spartacus Slave Revolt",
    year:       -73,
    yearMin:    -73,
    yearMax:    -71,
    lat:        40.916,
    lng:        15.537,
    loc:        "Capua, Campania, Italy",
    img:        'T3-017_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "1st Century BC",
    c3:         "Capua, Campania, Italy, Italy",
    desc:       "Spartacus Slave Revolt. Capua, Campania, Italy, 73\u201371 BC.",
    wikiImg:    "",
    wikiTitle:  "Spartacus Slave Revolt"
  },
  {
    id:         'T3-018',
    name:       "Inauguration of the Roman Colosseum",
    year:       80,
    lat:        41.8902,
    lng:        12.4922,
    loc:        "Colosseum (Flavian Amphitheatre), Rome",
    img:        'T3-018_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "1st Century AD",
    c3:         "Colosseum (Flavian Amphitheatre), Rome, Italy",
    desc:       "Inauguration of the Roman Colosseum. Colosseum (Flavian Amphitheatre), Rome, 80 AD.",
    wikiImg:    "",
    wikiTitle:  "Inauguration of the Roman Colosseum"
  },
  {
    id:         'T3-019',
    name:       "Construction of Machu Picchu",
    year:       1440,
    yearMin:    1440,
    yearMax:    1460,
    lat:        -13.1631,
    lng:        -72.545,
    loc:        "Machu Picchu, Cusco Region, Peru",
    img:        'T3-019_img1.png',
    yaw:        0,
    c1:         "South America",
    c2:         "15th Century AD",
    c3:         "Machu Picchu, Cusco Region, Peru, Peru",
    desc:       "Construction of Machu Picchu. Machu Picchu, Cusco Region, Peru, c. 1450 AD.",
    wikiImg:    "",
    wikiTitle:  "Construction of Machu Picchu"
  },
  {
    id:         'T3-020',
    name:       "Marco Polo Arrives at the Court of Kublai Khan",
    year:       1275,
    lat:        41.902,
    lng:        116.41,
    loc:        "Xanadu (Shangdu), Inner Mongolia, China",
    img:        'T3-020_img1.png',
    yaw:        0,
    c1:         "Asia",
    c2:         "13th Century AD",
    c3:         "Xanadu (Shangdu), Inner Mongolia, China, China (Inner Mongolia)",
    desc:       "Marco Polo Arrives at the Court of Kublai Khan. Xanadu (Shangdu), Inner Mongolia, China, 1275 AD.",
    wikiImg:    "",
    wikiTitle:  "Marco Polo Arrives at the Court of Kublai Khan"
  },
  {
    id:         'T3-021',
    name:       "Plague of Athens",
    year:       -430,
    yearMin:    -430,
    yearMax:    -426,
    lat:        37.965,
    lng:        23.72,
    loc:        "Piraeus and Athens, Greece",
    img:        'T3-021_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "5th Century BC",
    c3:         "Piraeus and Athens, Greece, Greece",
    desc:       "Plague of Athens. Piraeus and Athens, Greece, 430\u2013426 BC.",
    wikiImg:    "",
    wikiTitle:  "Plague of Athens"
  },
  {
    id:         'T3-022',
    name:       "Library of Alexandria at Its Height",
    year:       -280,
    yearMin:    -280,
    yearMax:    -200,
    lat:        31.2156,
    lng:        29.9553,
    loc:        "Alexandria, Egypt",
    img:        'T3-022_img1.png',
    yaw:        0,
    c1:         "Africa",
    c2:         "3rd Century BC",
    c3:         "Alexandria, Egypt, Egypt",
    desc:       "At its height around 250 BC, the Library of Alexandria \u2014 founded by Ptolemy I and expanded by his successors \u2014 was the largest accumulation of written knowledge in the ancient world, housing an estimated 400,000 to 700,000 papyrus scrolls covering every subject from mathematics and astronomy to drama and medicine, assembled through a deliberate policy of copying every book that passed through Alexandria's harbour. The Library was paired with the Mouseion, a research institution where scholars including Euclid, Archimedes, Eratosthenes (who calculated the Earth's circumference within 1% accuracy), and Aristarchus (who proposed that the Earth orbits the Sun) lived, worked, and drew salaries paid by the Ptolemaic state. The Library was not destroyed in a single dramatic fire \u2014 it declined gradually through neglect and political upheaval over several centuries \u2014 but its existence represents the ancient world's most ambitious attempt to gather all human knowledge in one place.",
    wikiImg:    "https://upload.wikimedia.org/wikipedia/commons/6/64/Ancientlibraryalex.jpg",
    wikiTitle:  "Library of Alexandria"
  },
  {
    id:         'T3-023',
    name:       "Bay of Pigs Invasion",
    year:       1961,
    yearMin:    1961,
    yearMax:    1961,
    lat:        22.0615,
    lng:        -81.1196,
    loc:        "Playa Gir\u00f3n, Bay of Pigs, Cuba",
    img:        'T3-023_img1.png',
    yaw:        0,
    c1:         "North America",
    c2:         "20th Century AD",
    c3:         "Playa Gir\u00f3n, Bay of Pigs, Cuba, Cuba",
    desc:       "On April 17, 1961, approximately 1,400 Cuban exiles trained and equipped by the CIA landed at the Bay of Pigs on Cuba's southern coast in an attempt to overthrow Fidel Castro's revolutionary government \u2014 and within 72 hours had been comprehensively defeated, with over 100 dead and more than 1,100 captured, in one of the most embarrassing covert operations in American history. The plan, inherited by President Kennedy from the Eisenhower administration, depended on a popular uprising that never materialised and on air support that Kennedy cancelled at the last minute fearing international exposure. The failure strengthened Castro's position domestically and internationally, pushed Cuba closer to the Soviet Union, and directly contributed to the conditions that produced the Cuban Missile Crisis eighteen months later.",
    wikiImg:    "https://upload.wikimedia.org/wikipedia/commons/6/63/Attack_near_Playa_Giron._April_19%2C_1961._-_panoramio.jpg",
    wikiTitle:  "Bay of Pigs Invasion"
  },
  {
    id:         'T3-024',
    name:       "Signing of the Treaty of Versailles \u2013 End of WWI",
    year:       1919,
    lat:        48.8048,
    lng:        2.1203,
    loc:        "Hall of Mirrors, Palace of Versailles",
    img:        'T3-024_img1.png',
    yaw:        0,
    c1:         "Europe",
    c2:         "20th Century AD",
    c3:         "Hall of Mirrors, Palace of Versailles, France",
    desc:       "On June 28, 1919 \u2014 exactly five years after the assassination of Archduke Franz Ferdinand that had triggered the war \u2014 representatives of Germany and the Allied powers signed the Treaty of Versailles in the Hall of Mirrors at the Palace of Versailles, formally ending the First World War and imposing on Germany sole responsibility for the conflict, massive reparations, territorial losses, and strict limits on its military. The German delegation signed under protest, and the treaty's punitive terms \u2014 particularly the 'war guilt clause' \u2014 generated lasting resentment in Germany that Adolf Hitler would systematically exploit in his rise to power. The historian Margaret MacMillan has argued that the treaty was neither harsh enough to permanently cripple Germany nor lenient enough to reconcile it to defeat, making a second European war not inevitable but distinctly more likely.",
    wikiImg:    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Treaty_of_Versailles%2C_English_version.jpg/3840px-Treaty_of_Versailles%2C_English_version.jpg",
    wikiTitle:  "Treaty of Versailles"
  }
];
